{% load_yaml as lookup %}
FreeBSD:
    package: openssh-portable
    service: sshd
    config_file: /etc/ssh/sshd_config
Debian:
    package: openssh-server
    service: ssh
    config_file: /etc/ssh/sshd_config
{% endload %}

{% load_yaml as rawmap %}
{% endload %}
